name: Deploy to Server

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key from GitHub Secrets
      run: |
        mkdir -p ~/.ssh
        echo "$PEM_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa  # Decode the base64 key and save it
        chmod 600 ~/.ssh/id_rsa  # Set correct permissions
        # Add the server's SSH key to known_hosts to avoid the "yes/no" prompt
        ssh-keyscan -H ${{ secrets.SERVER_URL }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        # Non-interactive SSH with proper key handling
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_URL }} << 'EOF'
          cd /home/ubuntu/projects/
          rm -rf y_fi_backend
          git clone https://github.com/snigdho48/y_fi_backend.git y_fi_backend
          cd y_fi_backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
