name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        echo "${{ secrets.PEM_FILE }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.SERVER_URL }} << 'EOF'
          cd /home/ubuntu/projects/
          sudo rm -rf y_fi_backend
          git clone https://github.com/snigdho48/y_fi_backend.git y_fi_backend
          cd y_fi_backend
          python3 -m venv venv
          source venv/bin/activate
          git checkout master
          pip install --upgrade pip
          ls
          pip install -r requirements.txt
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
        rm -f private_key.pem  # Cleanup after execution
