name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      env:
        PEM_PRIVATE_KEY: ${{ secrets.PEM_FILE }}
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -i <(echo "$PEM_PRIVATE_KEY") ubuntu@${{ secrets.SERVER_URL }} << 'EOF'
          cd /home/ubuntu/projects/
          rm -rf y_fi_backend
          git clone https://github.com/snigdho48/y_fi_backend.git y_fi_backend
          cd y_fi_backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
