name: Deploy to Server

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key using ssh-agent
      run: |
        mkdir -p ~/.ssh
        echo "$PEM_FILE" > ~/.ssh/id_rsa  # Write PEM secret to id_rsa file
        chmod 600 ~/.ssh/id_rsa  # Set correct file permissions
        eval $(ssh-agent -s)  # Start ssh-agent
        ssh-add ~/.ssh/id_rsa  # Add the private key to ssh-agent
        ssh-keyscan -H ${{ secrets.SERVER_URL }} >> ~/.ssh/known_hosts  # Add server's SSH key to known_hosts

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_URL }} << 'EOF'
          
          cd /home/ubuntu/projects/

          rm -rf y_fi_backend  # Remove the old project

          git clone https://github.com/snigdho48/y_fi_backend.git y_fi_backend  # Clone the latest version

          cd y_fi_backend

          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Install dependencies

          sudo systemctl restart gunicorn  # Restart Gunicorn
          sudo systemctl restart nginx  # Restart Nginx
        EOF
