name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        echo "${{ secrets.PEM_FILE }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.SERVER_URL }} << 'EOF'
          cd /home/ubuntu/projects/y_fi_backend
          git pull origin master
          source /home/ubuntu/projects/y_fi_backend/venv/bin/activate
          pip install -r requirements.txt
          sudo chown -R www-data:www-data /home/ubuntu/projects/y_fi_backend/static
          sudo chown -R ubuntu:www-data /home/ubuntu/projects/y_fi_backend/media
          sudo chmod -R 755 /home/ubuntu/projects/y_fi_backend/static
          sudo chmod -R 755 /home/ubuntu/projects/y_fi_backend/media
          sudo chmod 755 /home/ubuntu/projects
          sudo chmod 755 /home/ubuntu
          sudo chmod 755 /home
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          echo "Deployment successful"
        EOF
        rm -f private_key.pem  # Cleanup after execution
