name: Deploy to Server

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Clone repository
      run: |
        git clone https://github.com/snigdho48/y_fi_backend.git
        cd y_fi_backend
        git checkout master

    - name: Set up SSH key from PEM secret
      run: |
        mkdir -p ~/.ssh
        echo "$PEM_FILE" > ~/.ssh/id_rsa  # Use the PEM secret directly
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_URL >> ~/.ssh/known_hosts  # Use SERVER_URL secret here

    - name: Deploy to server
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$SERVER_URL << 'EOF'

          cd /home/ubuntu/projects/
          
          rm -rf y_fi_backend

          git clone https://github.com/snigdho48/y_fi_backend.git y_fi_backend

          cd y_fi_backend

          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF


